CREATE TABLE URLS(

    ID UUID PRIMARY KEY,
    SHORT_URL VARCHAR(10) UNIQUE NOT NULL,
    LONG_URL VARCHAR(600) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW()


);

CREATE TABLE RECORDS(

    ID UUID PRIMARY KEY,
    URL_ID UUID NOT NULL REFERENCES URLS(ID) ON DELETE CASCADE,
    CLICKED_AT TIMESTAMP DEFAULT NOW(),
    TIMEZONE VARCHAR(50),
    DEVICE VARCHAR(50),
    OS VARCHAR(50)
);